import { TranslationKeys, type TranslationValues } from "$lib/strings/keys";

const en: TranslationValues = {
	[TranslationKeys.SYMBOL]: "en",
	[TranslationKeys.NAME]: "English",
	[TranslationKeys.UI_DIRECTION]: "ltr",
	[TranslationKeys.TITLE_MAIN]: "Apollo Music",
	[TranslationKeys.TITLE_ABOUT]: "About - Apollo Music",
	[TranslationKeys.TITLE_RECENTS]: "Recents - Apollo Music",
	[TranslationKeys.TITLE_LIBRARY]: "Library - Apollo Music",
	[TranslationKeys.TITLE_LIBRARY_MUSIC]: "Music Library - Apollo Music",
	[TranslationKeys.TITLE_LIBRARY_MUSIC_SONGS]: "All Songs - Apollo Music",
	[TranslationKeys.TITLE_LIBRARY_MUSIC_ALBUMS]: "Albums - Apollo Music",
	[TranslationKeys.TITLE_LIBRARY_MUSIC_ARTISTS]: "Artists - Apollo Music",
	[TranslationKeys.TITLE_LIBRARY_MUSIC_YEARS]: "Songs Release Years - Apollo Music",
	[TranslationKeys.TITLE_LIBRARY_MUSIC_GENRERS]: "Genres - Apollo Music",
	[TranslationKeys.TITLE_EQUALIZER]: "Equalizer - Apollo Music",
	[TranslationKeys.TITLE_SETTINGS]: "Settings - Apollo Music",
	[TranslationKeys.TITLE_PLAYING_SUFFIX]: " - Apollo Music",
	[TranslationKeys.TITLE_SIGN_IN]: "Sign in - Apollo Music",
	[TranslationKeys.TITLE_RESET_PASSWORD]: "Reset password - Apollo Music",
	[TranslationKeys.TITLE_FORGOT_PASSWORD]: "Forgot password - Apollo Music",
	[TranslationKeys.SIGN_IN_HEADER]: "We've Missed you, welcome back!",
	[TranslationKeys.SIGN_IN_EMAIL]: "Email",
	[TranslationKeys.SIGN_IN_PASSWORD]: "Password",
	[TranslationKeys.SIGN_IN_BUTTON]: "Log in",
	[TranslationKeys.SIGN_IN_FORGOT_PASSWORD]: "Forgot password?",
	[TranslationKeys.SIGN_IN_SIGN_UP]: "New here? Discover the beat",
	[TranslationKeys.SIGN_IN_SIGN_UP_HERE]: "here",
	[TranslationKeys.FORGOT_PASSWORD_EMAIL]: "Email",
	[TranslationKeys.FORGOT_PASSWORD_BUTTON]: "Reset password",
	[TranslationKeys.PASSWORD_RESET_NEW_PASSWORD]: "Enter your new password",
	[TranslationKeys.PASSWORD_RESET_UPDATE_BUTTON]: "Update password",
	[TranslationKeys.LIBRARY_HEAD]: "Apollo Library",
	[TranslationKeys.LIBRARY_NAV_ALBUMS]: "Albums",
	[TranslationKeys.LIBRARY_NAV_ARTISTS]: "Artists",
	[TranslationKeys.LIBRARY_NAV_ALL_SONGS]: "All Songs",
	[TranslationKeys.LIBRARY_NAV_FAVORITES]: "Favorites",
	[TranslationKeys.LIBRARY_NAV_PLAYLISTS]: "Playlists",
	[TranslationKeys.LIBRARY_NAV_YEARS]: "Years",
	[TranslationKeys.LIBRARY_NAV_GENRES]: "Genres",
	[TranslationKeys.LIBRARY_NAV_UPLOAD]: "Upload",
	[TranslationKeys.PLAYER_NOW_PLAYING]: "Now Playing"
};

export default en;
