package helpers

import (
	"encoding/base64"
	goerrors "errors"
	"fmt"
	"io"
	"log"
	"mime/multipart"
	"os"
	"strings"
	"time"

	"github.com/dhowden/tag"

	"github.com/mbaraa/apollo-music/config/env"
	"github.com/mbaraa/apollo-music/data"
	"github.com/mbaraa/apollo-music/entities"
	"github.com/mbaraa/apollo-music/enums"
	"github.com/mbaraa/apollo-music/errors"
	"github.com/mbaraa/apollo-music/helpers/response"
	"github.com/mbaraa/apollo-music/models"
	"github.com/mbaraa/apollo-music/utils/jwt"
)

type UploadHelper struct {
	storageRepo data.CRUDRepo[models.Storage]
	userRepo    data.CRUDRepo[models.User]
	musicRepo   data.CRUDRepo[models.Music]
	albumRepo   data.CRUDRepo[models.MusicAlbum]
	artistRepo  data.CRUDRepo[models.MusicArtist]
	yearRepo    data.CRUDRepo[models.MusicReleaseYear]
	genreRepo   data.CRUDRepo[models.MusicGenre]
	jwtUtil     jwt.Manager[entities.JSON]
}

func NewUploadHelper(
	storageRepo data.CRUDRepo[models.Storage],
	userRepo data.CRUDRepo[models.User],
	musicRepo data.CRUDRepo[models.Music],
	albumRepo data.CRUDRepo[models.MusicAlbum],
	artistRepo data.CRUDRepo[models.MusicArtist],
	yearRepo data.CRUDRepo[models.MusicReleaseYear],
	genreRepo data.CRUDRepo[models.MusicGenre],
	jwtUtil jwt.Manager[entities.JSON],
) *UploadHelper {
	return &UploadHelper{
		storageRepo: storageRepo,
		userRepo:    userRepo,
		musicRepo:   musicRepo,
		albumRepo:   albumRepo,
		artistRepo:  artistRepo,
		yearRepo:    yearRepo,
		genreRepo:   genreRepo,
		jwtUtil:     jwtUtil,
	}
}

// TODO
// handle duplicate files
func (u *UploadHelper) UploadFile(token string, audioType enums.AudioType, fileHeader *multipart.FileHeader) (entities.JSON, int) {
	claims, err := u.jwtUtil.Decode(token, jwt.SessionToken)
	if err != nil {
		log.Println(err)
		return response.Build(errors.InvalidToken, nil)
	}

	if !strings.Contains(fileHeader.Header.Get("Content-Type"), "audio") {
		return response.Build(errors.BadRequest, nil)
	}

	dbUser, err := u.userRepo.GetByConds("email = ?", claims.Payload["email"])
	if err != nil {
		log.Println(err)
		return response.Build(errors.NotFound, nil)
	}

	dbStorage, err := u.storageRepo.GetByConds("user_id = ?", dbUser[0].Id)
	if err != nil {
		log.Println(err)
		return response.Build(errors.NotFound, nil)
	}

	if dbStorage[0].Size-dbStorage[0].Used < fileHeader.Size/(1024*1024) {
		return response.Build(errors.InsufficientStorage, nil)
	}

	saveDirectory := fmt.Sprintf("%s/%s/%s", env.MusicDirectory(), dbUser[0].PublicId, audioType.String())
	err = os.Mkdir(saveDirectory, 0755)
	if err != nil && !goerrors.Is(err, os.ErrExist) {
		return response.Build(errors.InternalServerError, nil)
	}

	file, err := fileHeader.Open()
	if err != nil {
		log.Println(err)
		return response.Build(errors.BadRequest, nil)
	}
	defer file.Close()

	filePath := fmt.Sprintf("%s/%s", saveDirectory, fileHeader.Filename)
	fileToSave, err := os.Create(filePath)

	_, err = io.Copy(fileToSave, file)
	if err != nil {
		log.Println(err)
		return response.Build(errors.InternalServerError, nil)
	}

	err = u.storageRepo.Update(&models.Storage{
		Used: dbStorage[0].Used + fileHeader.Size/(1024*1024),
	}, "id = ?", dbStorage[0].Id)
	if err != nil {
		log.Println(err)
		return response.Build(errors.InternalServerError, nil)
	}

	if audioType == enums.MusicType {
		_, _ = file.Seek(0, 0)
		musicMetaData, err := tag.ReadFrom(file)
		if err != nil {
			log.Println(err)
			musicMetaData = &defaultMusicValues{fileHeader.Filename[:strings.Index(fileHeader.Filename, ".")]}
		}

		title := musicMetaData.Title()
		album := musicMetaData.Album()
		year := musicMetaData.Year()
		genre := musicMetaData.Genre()
		artist := musicMetaData.AlbumArtist()
		if len(artist) == 0 {
			artist = musicMetaData.Artist()
		}
		trackNumber, _ := musicMetaData.Track()

		_dbArtist := models.MusicArtist{
			Name:   artist,
			UserId: dbUser[0].Id,
		}
		_dbYear := models.MusicReleaseYear{
			Name:   fmt.Sprint(year),
			UserId: dbUser[0].Id,
		}
		_dbGenre := models.MusicGenre{
			Name:   genre,
			UserId: dbUser[0].Id,
		}

		dbArtist, err := u.artistRepo.GetByConds("name = ?", artist)
		if err != nil {
			err = u.artistRepo.Add(&_dbArtist)
			if err != nil {
				log.Println(err)
				return response.Build(errors.InternalServerError, nil)
			}
		} else {
			_dbArtist = dbArtist[0]
		}

		dbYear, err := u.yearRepo.GetByConds("name = ?", year)
		if err != nil {
			err = u.yearRepo.Add(&_dbYear)
			if err != nil {
				log.Println(err)
				return response.Build(errors.InternalServerError, nil)
			}
		} else {
			_dbYear = dbYear[0]
		}

		dbGenre, err := u.genreRepo.GetByConds("name = ?", genre)
		if err != nil {
			err = u.genreRepo.Add(&_dbGenre)
			if err != nil {
				log.Println(err)
				return response.Build(errors.InternalServerError, nil)
			}
		} else {
			_dbGenre = dbGenre[0]
		}

		var albumCoverB64 string
		if musicMetaData.Picture() == nil || len(musicMetaData.Picture().Type) == 0 {
			albumCoverB64 = getDefaultAlbumCover()
		} else {
			albumCoverB64 = uploadAlbumCover(musicMetaData.Picture().Data)
		}

		_dbAlbum := models.MusicAlbum{
			UserId:     dbUser[0].Id,
			Title:      album,
			ArtistName: artist,
			ArtistId:   _dbArtist.Id,
			Year:       fmt.Sprint(year),
			YearId:     _dbYear.Id,
			Genre:      genre,
			CoverB64:   albumCoverB64,
			GenreId:    _dbGenre.Id,
		}
		dbAlbum, err := u.albumRepo.GetByConds("title = ?", album)
		if err != nil {
			err = u.albumRepo.Add(&_dbAlbum)
			if err != nil {
				log.Println(err)
				return response.Build(errors.InternalServerError, nil)
			}
		} else {
			_dbAlbum = dbAlbum[0]
		}

		_dbMusic := models.Music{
			UserId:      dbUser[0].Id,
			Title:       title,
			AlbumTitle:  album,
			AlbumId:     _dbAlbum.Id,
			ArtistName:  artist,
			ArtistId:    _dbArtist.Id,
			Year:        fmt.Sprint(year),
			YearId:      _dbYear.Id,
			Genre:       genre,
			GenreId:     _dbGenre.Id,
			TrackNumber: trackNumber,
			Audio: models.Audio{
				FileName:    fileHeader.Filename,
				FileSize:    fileHeader.Size / (1024 * 1024),
				AccessTimes: 0,
				LastAccess:  time.Now(),
				PublicPath:  fmt.Sprintf("%s/%s/%s", dbUser[0].PublicId, audioType.String(), fileHeader.Filename),
				Type:        audioType,
			},
		}
		dbMusic, err := u.musicRepo.GetByConds("title = ?", title)
		if err != nil {
			err = u.musicRepo.Add(&_dbMusic)
			if err != nil {
				log.Println(err)
				return response.Build(errors.InternalServerError, nil)
			}
		} else {
			_dbMusic = dbMusic[0]
		}
	}

	return response.Build(errors.None, nil)
}

func uploadAlbumCover(imageData []byte) string {
	imageB64 := base64.StdEncoding.EncodeToString(imageData)
	return imageB64
}

func getDefaultAlbumCover() string {
	return "/9j/4AAQSkZJRgABAQEAYABgAAD/4RD4RXhpZgAATU0AKgAAAAgABAE7AAIAAAAPAAAISodpAAQAAAABAAAIWpydAAEAAAAeAAAQ0uocAAcAAAgMAAAAPgAAAAAc6gAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE5hdGhhbiBTaHJvZGVyAAAABZADAAIAAAAUAAAQqJAEAAIAAAAUAAAQvJKRAAIAAAADNDAAAJKSAAIAAAADNDAAAOocAAcAAAgMAAAInAAAAAAc6gAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADIwMTg6MTI6MjEgMTA6NTc6MTEAMjAxODoxMjoyMSAxMDo1NzoxMQAAAE4AYQB0AGgAYQBuACAAUwBoAHIAbwBkAGUAcgAAAP/hCyFodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvADw/eHBhY2tldCBiZWdpbj0n77u/JyBpZD0nVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkJz8+DQo8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIj48cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPjxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSJ1dWlkOmZhZjViZGQ1LWJhM2QtMTFkYS1hZDMxLWQzM2Q3NTE4MmYxYiIgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIi8+PHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9InV1aWQ6ZmFmNWJkZDUtYmEzZC0xMWRhLWFkMzEtZDMzZDc1MTgyZjFiIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iPjx4bXA6Q3JlYXRlRGF0ZT4yMDE4LTEyLTIxVDEwOjU3OjExLjM5NzwveG1wOkNyZWF0ZURhdGU+PC9yZGY6RGVzY3JpcHRpb24+PHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9InV1aWQ6ZmFmNWJkZDUtYmEzZC0xMWRhLWFkMzEtZDMzZDc1MTgyZjFiIiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iPjxkYzpjcmVhdG9yPjxyZGY6U2VxIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+PHJkZjpsaT5OYXRoYW4gU2hyb2RlcjwvcmRmOmxpPjwvcmRmOlNlcT4NCgkJCTwvZGM6Y3JlYXRvcj48L3JkZjpEZXNjcmlwdGlvbj48L3JkZjpSREY+PC94OnhtcG1ldGE+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgIDw/eHBhY2tldCBlbmQ9J3cnPz7/2wBDAAcFBQYFBAcGBQYIBwcIChELCgkJChUPEAwRGBUaGRgVGBcbHichGx0lHRcYIi4iJSgpKywrGiAvMy8qMicqKyr/2wBDAQcICAoJChQLCxQqHBgcKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKir/wAARCADyAPADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDww+9GKWkrrMBKKWkoASg0ppKAEopaSkMSilooASkpTSUgEopaKBiUUtJQAUlLRSGJRRRQAlFLRSGJRRRQAUlLRQAlFFFABR06UUUAWqKWkrQzEpDTqSkMSilpKAEopaQ0gCkpaSgBKKWjFAxKKWkoASiiikMKSlooASilpKQCUUtFACUYoooGJRS0UAJRS0UgEooooAtUUtFaGY2ilooGNxRS0lIAxTadSYoASilooGJikpaKQxKKWkoASilooASijFFIYlGKWigQlFFFIYlGKWigBKSlooASilooASilpKALdJiloqyBKSlooAbRS0YoGNxRTqSkAlJS0UDEpKdSUgEopaKAEpKWigYlFLRQAlJS0UgEopaKAEpKWigBKKWigBKKWkoASloopAWqSlorQgbRS4ooGJRilpKQCGk70tGKBiUUtJSASilooGJSUtFACUYqWO3mmGYopHH+ypNNkhkhbEsbIfRlxSAZSU6koASiloxQAlFFFACUUpFJQMSilooASilopAJRS0mKALVGKWirIEpKWkoGJSU6koATFJTqKQDcUUtFACU+C3murhILWJ5pZDtSONSzMfQAVLYWFzqeoQ2NhC09zO4SONBksTX098OPhnY+C7Fbm6RLjV5VHmzkZEX+ynp7nvUt2GefeEPgHc3caXfi65azQ4Is7cgyEf7TdF+gz+Fes6N8P/CugIo03RLRXXpLKnmyf99Nk10dFRdlCKqooVAFUdABjFNlhinjKTxpIh6q6gj8jT6KQHH678LPCGvo3n6RDazN0msx5LA+uF4P4g14141+CWseHY5L3RHbVbBBuYKuJox7qPvD3H5V9K0U7sD4cIIJBGDSV9DfFX4SxatDNrnhmAR36jdPaxrhZx6qOzfz+tfPZBBIIwRVp3ENopaKAExxSUp4ooASilooASkpcUUAJRS0UgLRpKXvRirJG0UtFACYpKdSUAJSUtFAxKSnVoeH9JfXPEen6XHwbu4SIn+6CeT+AyaQHt/wM8EpY6T/AMJNfxA3V4CtqGH+rjyQW+rfyA9a9fqK1torOzhtbZAkMMaxxqBwqgYA/IVLWZQUUyeaO2t5J7h1jiiUu7scBVAySfwr5v8AiN8XNR8Q3s+naDcSWekoxTfExV7kepI5Cn09OtCVwPfL7xZ4e0yQx6hrmnW0g6xyXSBvyzmp9O8QaPq5xpWq2V6R1FvcI5H4A18X0+KWW3mSWCRo5EOVdGIKn1BHSq5RXPt2ivEPhX8Xri6voNA8Vz+a0p2W19IfmLdkc989A3rjPrXt9SMK+dfjh4HTRNYTX9NiCWd+5WZEHEUuOv0bk/UGvoqsDxxoK+JfBOp6ZtDSSQFocjOJF+Zf1AH40ID48oxS4oqxDaKWjFACUmKWigBKDS0UAJSUtFIC1RS0VZI3FGKWkoGJSYp1JSASilpKAExXffBS0W5+KNi7jP2eKWUAjvsKj/0KuCr0b4FyBPiXGD1e0lUfXAP9KT2GfS9FFFZlHmvxz1uTS/AP2SBir6jOIGI/uAFm/PAH4181V9BftC2kkvhfS7pVJSG7KuR0G5eP/Qa+fqtbEs3fC/gvXPGE8sehWnnCEAySO4REz0GT39hVHXNB1Hw3qsmnazbNbXMYBKkggg9CCOCK9E+EPxH0rwfaXuna4kscNxKJo54k34OMFWA57DHXvWD8U/Glr428UR3WmwvHaW0AgjaQYaT5iS2Ow54H+NHUDilZkYOjFWU5BBwQa+vvAmtSeIfAuk6nOd000AErH+J1JVj+JUmvkCvqz4R2j2fwr0ZJQQzpJLg+jyMw/Qikxo7OiiipGfGnim0Fj4w1i0XAWC+mjGPQSECsmt7xxKs3j/X5E5U6jPg+v7w1hVZIlJTiKSgBKKXFFADaKXFFACUYpaKALVJSmg1QhKTFLRQA2ilooASkpTRQMSul+HWqrovxD0a9kbZGLgRSH0VwUJP03Zrm6ASpBBII5BpAfbdFcp8N/FaeLfBtrdM6m8gUQ3Sg8hxxn/gQwfxrq6zKMfxX4dt/FXhm80m6+UTp8j/3HHKt+Br5K13Q77w7rE+mapCYriFiDnow7MD3B9a+zawfFHgzRPGFosGtWu9k/wBXPGdskf0b09jkU0xHx/RXtt/+zs/nMdM8QL5f8K3FvyPxB5/IVa0j9nq1iuBJretSXEYP+ptovLz9WJP8qdwseX+A/Bd5408RRWkKMlnGwa6nx8qIO31PQfWvrK1torO0htbZBHDCixxoOiqBgD8hVTRdD03w9psdho9qltbxjhV6sfUnqT7mtCkMKralfRaZpd1fXDBYraJpXJOOFGas15T8dfFi6Z4aTQbWT/StROZgP4IQefzOB9AaQHz3d3L3l7Pcy/fmkaRvqTk/zqGloqxCUUuKKAExRS0lIBKKWigBO1FFFAi1SU6kqwEopcUlIBDRS0lACUYpcUUANopaKQHVfD7xtceCfES3I3SWM5CXcI/iX+8P9oZJH5d6+ptL1Oz1nTIL/TZ1ntp13I6nr/8AX7V8X4rrfA3xD1TwReH7P/pNhIf31o7YB/2lP8JpMZ9W0Vz3hbx1oPi+3D6TeL54+/aykLKv/Ae49xkV0VSMSilpKACiiuI8afFTQvCUMkKTLf6ltOy2gYEKf9tui/z9qANvxb4r07wfoUmo6nJz92GEH5pn7KP6nsK+UfEWvXnibXbnVNSfdNO2cZ4Reyj2Aqx4p8Vap4u1h7/V5t7dIol4SJf7qj+vU1i1QhuKKWigBKKXFJQAlFLRQAlFLSdqAEpKdSUAW6SlxQaoQ2jFLQaQDcUUtJQAUUtJ1oGJjNFLikpAFJTqTFADopZIJllhkaORDlXQkFT6giu10f4v+MdHVY/7SF9EvRL1PM/8e4b9a4ijFAHrcP7Qmtqg+0aPp7t6ozqPyJNR3P7QWvuuLTStOiPq4d//AGYV5RikosgOr1v4meLdfVo7zV5YoG6w22IVI9Dt5I+pNcnTqSgBKKWigBtFGKWgBtFLRigBKTFLRQAlFLRQA00UtJigC3SUpopgIRSUvaikAmKTFLiimAlGKMUUgExRilNFACUUtFACYopaMUANopaKAExRiloxQAlFLSGgBtFLRQAlFLSUAJRS0lACUUtJSAKSlpKYFujmlxRigBuKMUtFACUmKWigBKMUtFADcUY4paKAExRS0Y96AExSU6koASilooATFIRS0UAIaKWkoASilpKQBSEUtGKAEpKWigBKSlooEJSUtFMC3iilNJ9aBiYopaKBiUn0paKQhKSlxRQAlGKWigBKSnUlACYoxS0UAIRRS4pKAEopaKAEpDS0GgBtFLjFFACUlLRQISkpaKAEooooASkp2KTrTAuGkpaTFIoSilooASkp1GKAG0UtFADcUUuKMYoAKSloxQITFFFFACUUtGKAExSUtFACUlOxSUAIaSlooEJRRRQAlFFB4oGJSUveigQlFFFMC52o7iiikUIaaaKKAFoNFFACdqO1FFAgpKKKBijpSCiigQCg0UUAA60lFFACdqB1oooAD1oNFFACHtRRRQIbR2oooAPSg/1oooAQ0dqKKYCDrR2oooA//9k="
}

// defaultMusicValues implements tag.Metadata for default music metadata values
type defaultMusicValues struct {
	title string
}

func (d *defaultMusicValues) Format() tag.Format { return tag.Format("") }

func (d *defaultMusicValues) FileType() tag.FileType { return tag.FileType("") }

func (d *defaultMusicValues) Title() string { return d.title }

func (d *defaultMusicValues) Album() string { return "Unknown Album" }

func (d *defaultMusicValues) Artist() string { return "Unknown Artist" }

func (d *defaultMusicValues) AlbumArtist() string { return "Unknown Artist" }

func (d *defaultMusicValues) Composer() string { return "Unknown Composer" }

func (d *defaultMusicValues) Year() int { return 0 }

func (d *defaultMusicValues) Genre() string { return "Unknown Genre" }

func (d *defaultMusicValues) Track() (int, int) { return 0, 0 }

func (d *defaultMusicValues) Disc() (int, int) { return 0, 0 }

func (d *defaultMusicValues) Picture() *tag.Picture { return nil }

func (d *defaultMusicValues) Lyrics() string { return "" }

func (d *defaultMusicValues) Comment() string { return "" }

func (d *defaultMusicValues) Raw() map[string]interface{} { return nil }
